import { defaultMapping, type Scene } from '../types/scene'

const now = () => Date.now()

const baseSenseBindings = () => [
  { source: 'hand.index' as const, target: 'organism.speed', range: [0.5, 2.0] as [number, number] },
  { source: 'audio.bass' as const, target: 'organism.size', range: [0.5, 2.5] as [number, number] },
]

export const defaultScenes: Scene[] = [
  {
    id: 'plankton',
    name: '🌊 Plancton bioluminescent',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'boids',
      values: { count: 1800, cohesion: 0.6, separation: 0.7, alignment: 0.5, speed: 0.7, vision: 0.4, size: 0.015, trail: 0.92 },
    },
    visual: {
      palette: { bg: '#020611', primary: '#00ffa3', secondary: '#00d4ff', glow: '#7c3aed' },
      bloom: 0.6, feedback: 0.93, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: baseSenseBindings() },
    evolution: { enabled: true, driftSpeed: 0.05, amplitude: 0.15 },
    mapping: defaultMapping(),
    notes: 'Inspiré du plancton bioluminescent. La main attire le banc, les graves font respirer les agents.',
  },
  {
    id: 'mycelium',
    name: '🍄 Mycélium pulsé',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'tendrils',
      values: { count: 32, length: 48, speed: 0.45, twist: 1.6, thickness: 0.01, trail: 0.95 },
    },
    visual: {
      palette: { bg: '#080205', primary: '#ff6ba6', secondary: '#7c3aed', glow: '#ffd54f' },
      bloom: 0.5, feedback: 0.95, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Tendrils qui s\'enroulent et se cherchent. La main les attire ; les médiums modulent leur vitesse.',
  },
  {
    id: 'stardust',
    name: '✨ Poussière d\'étoiles',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'particles',
      values: { count: 4000, speed: 0.6, size: 1.2, spread: 1.2, trail: 0.88, gravity: -0.2, turbulence: 0.7 },
    },
    visual: {
      palette: { bg: '#010013', primary: '#ffffff', secondary: '#9be7ff', glow: '#ffe5a8' },
      bloom: 0.4, feedback: 0.88, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: true, driftSpeed: 0.08, amplitude: 0.2 },
    mapping: defaultMapping(),
    notes: 'Particules génératives. Le main attire/pousse selon le pinch.',
  },
  {
    id: 'colony',
    name: '🧫 Colonie cellulaire',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'cells',
      values: { count: 60, pulse: 1.2, size: 1.4, attraction: 0.6, repulsion: 0.7, trail: 0.85 },
    },
    visual: {
      palette: { bg: '#030610', primary: '#7c3aed', secondary: '#00d4ff', glow: '#ff6ba6' },
      bloom: 0.5, feedback: 0.85, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: true, bindings: [] },
    evolution: { enabled: true, driftSpeed: 0.03, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Colonie de cellules qui pulsent au rythme des basses.',
  },
  {
    id: 'galaxy-trip',
    name: '🌀 Galaxie psychédélique',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'psychedelic',
      values: { count: 4900, speed: 1.2, freq: 5, scale: 1, trail: 0.95, size: 2.5 },
    },
    visual: {
      palette: { bg: '#020207', primary: '#7c3aed', secondary: '#ff6ba6', glow: '#ffd54f' },
      bloom: 0.7, feedback: 0.95, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Tunnel psychédélique — basé sur l\'équation paramétrique p5.js classique. La main décale le centre, le pinch accélère, les graves pulsent. Active le micro et mets de la musique : c\'est hypnotique.',
  },
  {
    id: 'mandala-vivant',
    name: '🪷 Mandala vivant',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'mandala',
      values: { arms: 12, pointsPerArm: 80, outerRadius: 0.9, innerRadius: 0.08, waves: 4, freq: 0.8, rotation: 0.25, thickness: 0.012, layers: 3, connectors: 3, connectorOpacity: 0.5 },
    },
    visual: {
      palette: { bg: '#070314', primary: '#00d4ff', secondary: '#ffd54f', glow: '#ff6ba6' },
      bloom: 0.6, feedback: 0.92, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Kaléidoscope sacré — bouge la main horizontalement pour changer le nombre de bras (3-16). Pinch ouvre le centre. Méditatif.',
  },
  {
    id: 'julia-explorer',
    name: '🌌 Julia infinie',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'fractal',
      values: { iterations: 140, zoom: 1, cx: -0.7269, cy: 0.1889, followHand: 0.4, bailout: 4, brightness: 1.0, orbitSpeed: 0.4, orbitRadius: 0.15, rotation: 0.12, zoomBreath: 0.08 },
    },
    visual: {
      palette: { bg: '#000000', primary: '#7c3aed', secondary: '#00ffa3', glow: '#ffd54f' },
      bloom: 0.5, feedback: 0.9, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Julia set GPU plein écran. La main pilote en live le paramètre c — morphe la forme fractale en temps réel. Pinch zoome. Explore l\'infini.',
  },
  {
    id: 'lissajous-dance',
    name: '∞ Lissajous',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'mathcurve',
      values: { formula: 'lissajous' as const, samples: 2000, cycles: 1, a: 3, b: 5, c: 1, d: 0.6, scale: 0.85, speed: 0.4, thickness: 0.006, lineOpacity: 0.7 },
    } as any,
    visual: {
      palette: { bg: '#000010', primary: '#00ffa3', secondary: '#00d4ff', glow: '#ffd54f' },
      bloom: 0.6, feedback: 0.93, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Lissajous 3:5 avec phase animée. Bouge la main pour morpher la figure. Change la formule pour Rose / Spirograph / Butterfly / Lorenz.',
  },
  {
    id: 'coral-rd',
    name: '🪸 Coral Reaction-Diffusion',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'reactiondiffusion',
      values: { preset: 'coral' as const, F: 0.029, k: 0.057, du: 1, dv: 0.5, resolution: 512, stepsPerFrame: 10, splatSize: 0.04, splatStrength: 0.9, contrast: 1.6 },
    } as any,
    visual: {
      palette: { bg: '#02080a', primary: '#00d4ff', secondary: '#7c3aed', glow: '#00ffa3' },
      bloom: 0.5, feedback: 0.9, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Gray-Scott simulation GPU. La main peint des cellules vivantes, audio bass nourrit la croissance. Change le preset (mitosis, fingerprint, worms...) pour explorer.',
  },
  {
    id: 'conway-life',
    name: '⬛ Conway',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'cellularautomata',
      values: { rule: 'conway' as const, resolution: 256, ticksPerSec: 14, ageDecay: 0.94, brushSize: 0.03, brushStrength: 0.6, autoReseed: 0.5 },
    } as any,
    visual: {
      palette: { bg: '#000000', primary: '#00ffa3', secondary: '#ffd54f', glow: '#ff6ba6' },
      bloom: 0.4, feedback: 0.85, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Conway Game of Life GPU avec trail âge. La main dessine des cellules, audio bass kick = reseed aléatoire. Essaie les règles HighLife / Daedalus / Replicator.',
  },
  {
    id: 'menger-sponge',
    name: '🧊 Éponge de Menger',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'menger',
      values: { depth: 3, autoOrbitSpeed: 0.4, fov: 55, twistAmount: 0.4, cubeSize: 0.95, ambient: 0.4, bloom: 0.3 },
    } as any,
    visual: {
      palette: { bg: '#02050a', primary: '#00d4ff', secondary: '#7c3aed', glow: '#ffd54f' },
      bloom: 0.5, feedback: 0.9, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Fractale cubique 3D (8000 cubes). Bouge la main pour orbiter, pinch pour zoomer, mets du son avec des graves pour pulser. Profondeur 4 = 160k cubes (lent, beau).',
  },
  {
    id: 'alien-flower',
    name: '🌐 Créature SuperShape',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'supershape3d',
      values: { m1: 6, n1: 0.6, n2: 0.5, n3: 1.5, m2: 8, n4: 0.6, n5: 0.5, n6: 1.5, resolution: 80, scale: 1, autoOrbitSpeed: 0.4, fov: 55, morphSpeed: 0.4, pointSize: 2, wireframe: 1 },
    } as any,
    visual: {
      palette: { bg: '#06010d', primary: '#ff6ba6', secondary: '#00d4ff', glow: '#ffd54f' },
      bloom: 0.6, feedback: 0.92, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Surface 3D paramétrique (Paul Bourke). Bouge la main verticalement pour morpher la symétrie en live → fleurs, étoiles, créatures alien. Audio bass = rondeur, morphSpeed = auto-évolution.',
  },
  {
    id: 'hilbert-net',
    name: '🌀 Hilbert Network',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'hilbert',
      values: { order: 5, scale: 1, progress: 1, autoProgress: 0.2, rotation: 0.08, thickness: 0.005, handPull: 0.5, showPoints: 1, hueAlongCurve: 0.6 },
    } as any,
    visual: {
      palette: { bg: '#000010', primary: '#00d4ff', secondary: '#7c3aed', glow: '#ffd54f' },
      bloom: 0.5, feedback: 0.92, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Courbe de Hilbert fractale auto-dessinée (1024 points). La main attire la courbe, autoProgress crée un sweep continu. Augmente l\'ordre pour plus de détail.',
  },
  {
    id: 'spirograph-flower',
    name: '🌹 Spirograph fleur',
    createdAt: now(),
    updatedAt: now(),
    organism: {
      kind: 'mathcurve',
      values: { formula: 'spirograph' as const, samples: 2500, cycles: 5, a: 6, b: 5, c: 2, d: 1.5, scale: 0.7, speed: 0.3, thickness: 0.005, lineOpacity: 0.75 },
    } as any,
    visual: {
      palette: { bg: '#1a0010', primary: '#ff6ba6', secondary: '#7c3aed', glow: '#ffd54f' },
      bloom: 0.5, feedback: 0.94, blendMode: 'add',
    },
    senses: { hands: true, audio: true, light: false, bindings: [] },
    evolution: { enabled: false, driftSpeed: 0.02, amplitude: 0.1 },
    mapping: defaultMapping(),
    notes: 'Spirograph hypotrochoid — change a/b pour voir les pétales évoluer. La main décale les paramètres en live.',
  },
]
